"""add_ai_memory

Revision ID: 047067e350a6
Revises: 2d6372cf94e5
Create Date: 2026-08-01 22:32:26.256797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047067e350a6'
down_revision: Union[str, Sequence[str], None] = '2d6372cf94e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=100), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_memories_customer_id'), 'ai_memories', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_memories_id'), 'ai_memories', ['id'], unique=False)
    op.create_index(op.f('ix_ai_memories_organization_id'), 'ai_memories', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_memories_organization_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_id'), table_name='ai_memories')
    op.drop_index(op.f('ix_ai_memories_customer_id'), table_name='ai_memories')
    op.drop_table('ai_memories')
    # ### end Alembic commands ###
