"""add_ai_decision_logs

Revision ID: 2c9205ab9ad4
Revises: b5cecb5f8001
Create Date: 2026-08-01 23:04:15.008290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9205ab9ad4'
down_revision: Union[str, Sequence[str], None] = 'b5cecb5f8001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_decision_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('decision_data', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('executed', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_decision_logs_action'), 'ai_decision_logs', ['action'], unique=False)
    op.create_index(op.f('ix_ai_decision_logs_customer_id'), 'ai_decision_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_decision_logs_id'), 'ai_decision_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_decision_logs_id'), table_name='ai_decision_logs')
    op.drop_index(op.f('ix_ai_decision_logs_customer_id'), table_name='ai_decision_logs')
    op.drop_index(op.f('ix_ai_decision_logs_action'), table_name='ai_decision_logs')
    op.drop_table('ai_decision_logs')
    # ### end Alembic commands ###
