"""add_ai_thought_logs

Revision ID: 3b486d4e5f76
Revises: ac28262d4973
Create Date: 2026-08-02 03:19:05.878339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b486d4e5f76'
down_revision: Union[str, Sequence[str], None] = 'ac28262d4973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_thought_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_thought_logs_customer_id'), 'ai_thought_logs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_thought_logs_id'), 'ai_thought_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_thought_logs_stage'), 'ai_thought_logs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_thought_logs_stage'), table_name='ai_thought_logs')
    op.drop_index(op.f('ix_ai_thought_logs_id'), table_name='ai_thought_logs')
    op.drop_index(op.f('ix_ai_thought_logs_customer_id'), table_name='ai_thought_logs')
    op.drop_table('ai_thought_logs')
    # ### end Alembic commands ###
