"""add_priority_scores

Revision ID: 6410652908b5
Revises: 9a657b6c7c4b
Create Date: 2026-08-01 22:46:58.632529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6410652908b5'
down_revision: Union[str, Sequence[str], None] = '9a657b6c7c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priority_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_priority_scores_customer_id'), 'priority_scores', ['customer_id'], unique=False)
    op.create_index(op.f('ix_priority_scores_id'), 'priority_scores', ['id'], unique=False)
    op.create_index(op.f('ix_priority_scores_organization_id'), 'priority_scores', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priority_scores_organization_id'), table_name='priority_scores')
    op.drop_index(op.f('ix_priority_scores_id'), table_name='priority_scores')
    op.drop_index(op.f('ix_priority_scores_customer_id'), table_name='priority_scores')
    op.drop_table('priority_scores')
    # ### end Alembic commands ###
