"""add_ai_event_store

Revision ID: 6c5aecc75706
Revises: 71c94e99b62b
Create Date: 2026-08-02 05:03:00.343033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5aecc75706'
down_revision: Union[str, Sequence[str], None] = '71c94e99b62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_id'), 'mission_events', ['id'], unique=False)
    op.create_index(op.f('ix_mission_events_level'), 'mission_events', ['level'], unique=False)
    op.create_index(op.f('ix_mission_events_source'), 'mission_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(op.f('ix_mission_events_source'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_level'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_id'), table_name='mission_events')
    op.drop_table('mission_events')
