"""add_ai_thought_logs

Revision ID: 71c94e99b62b
Revises: 3b486d4e5f76
Create Date: 2026-08-02 04:53:19.468550

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '71c94e99b62b'
down_revision: Union[str, Sequence[str], None] = '3b486d4e5f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
