"""add_ai_execution_queue

Revision ID: ac28262d4973
Revises: 2c9205ab9ad4
Create Date: 2026-08-01 23:09:21.084366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac28262d4973'
down_revision: Union[str, Sequence[str], None] = '2c9205ab9ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_execution_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_execution_queue_action'), 'ai_execution_queue', ['action'], unique=False)
    op.create_index(op.f('ix_ai_execution_queue_id'), 'ai_execution_queue', ['id'], unique=False)
    op.create_index(op.f('ix_ai_execution_queue_status'), 'ai_execution_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_execution_queue_status'), table_name='ai_execution_queue')
    op.drop_index(op.f('ix_ai_execution_queue_id'), table_name='ai_execution_queue')
    op.drop_index(op.f('ix_ai_execution_queue_action'), table_name='ai_execution_queue')
    op.drop_table('ai_execution_queue')
    # ### end Alembic commands ###
