"""add_customer_timeline

Revision ID: b5cecb5f8001
Revises: 6410652908b5
Create Date: 2026-08-01 22:50:19.282987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cecb5f8001'
down_revision: Union[str, Sequence[str], None] = '6410652908b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_timeline_customer_id'), 'customer_timeline', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_timeline_event_type'), 'customer_timeline', ['event_type'], unique=False)
    op.create_index(op.f('ix_customer_timeline_id'), 'customer_timeline', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_timeline_id'), table_name='customer_timeline')
    op.drop_index(op.f('ix_customer_timeline_event_type'), table_name='customer_timeline')
    op.drop_index(op.f('ix_customer_timeline_customer_id'), table_name='customer_timeline')
    op.drop_table('customer_timeline')
    # ### end Alembic commands ###
