"""add_ai_events

Revision ID: f83ac22ae440
Revises: 047067e350a6
Create Date: 2026-08-01 22:35:19.874087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83ac22ae440'
down_revision: Union[str, Sequence[str], None] = '047067e350a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_events_customer_id'), 'ai_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ai_events_id'), 'ai_events', ['id'], unique=False)
    op.create_index(op.f('ix_ai_events_organization_id'), 'ai_events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_events_organization_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_id'), table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_customer_id'), table_name='ai_events')
    op.drop_table('ai_events')
    # ### end Alembic commands ###
